# Use the official Rust image
FROM rust:latest

# Set the working directory
WORKDIR /usr/src/myapp

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

# Run formatting
RUN rustup component add rustfmt
RUN cargo fmt

# Run Clippy
RUN rustup component add clippy
RUN cargo clippy

# Run tests
RUN cargo test

ENV RUST_LOG=info

# Run the application
ENTRYPOINT ["cargo", "run"]
